# Generated by Django 5.0.1 on 2024-01-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
